export const CLAIM_STATUSES = {
  DRAFT: 'DRAFT',
  DEPARTMENT_REVIEW: 'DEPARTMENT_REVIEW',
  PRINCIPAL_REVIEW: 'PRINCIPAL_REVIEW',
  RPC_VERIFICATION: 'RPC_VERIFICATION',
  ACCOUNTS_PROCESSING: 'ACCOUNTS_PROCESSING',
  COMPLETED: 'COMPLETED',
  RETURNED: 'RETURNED',
  REJECTED: 'REJECTED'
};

export const TERMINAL_STATUSES = [CLAIM_STATUSES.COMPLETED, CLAIM_STATUSES.REJECTED];
export const ACTIVE_STATUSES = [
  CLAIM_STATUSES.DRAFT,
  CLAIM_STATUSES.DEPARTMENT_REVIEW,
  CLAIM_STATUSES.PRINCIPAL_REVIEW,
  CLAIM_STATUSES.RPC_VERIFICATION,
  CLAIM_STATUSES.ACCOUNTS_PROCESSING,
  CLAIM_STATUSES.RETURNED
];
